In [1]:
import whisper
import pandas as pd
import os

In [17]:
data_folder=r'..\data\audiodata'
all_dfs=[]
for file in  os.listdir(data_folder):
    if file.endswith('.csv'):
        path=os.path.join(data_folder,file)
        df=pd.read_csv(path,encoding='utf-8')
        df=df.iloc[0:30,:3]
        df['participant']=file #mark which participant(file)
        all_dfs.append(df)
data=pd.concat(all_dfs,ignore_index=True)
data.head()

,Sentence,Stimulus,Transcription,participant
0,1.0,Quiero cortarme el pelo (7),NaN,participant1.csv
1,2.0,El libro está en la mesa (7),NaN,participant1.csv
2,3.0,El carro lo tiene Pedro (8),NaN,participant1.csv
3,4.0,El se ducha cada mañana (9),NaN,participant1.csv
4,5.0,¿Qué dice usted que va a hacer hoy? (9),NaN,participant1.csv

In [18]:
data.shape

(120, 4)

In [19]:
import re

In [20]:
def clean(text):
    return re.sub(r"\s*\(.*?\)","",str(text)).strip()

In [21]:
data['Stimulus']=data['Stimulus'].apply(clean)
data.head()

,Sentence,Stimulus,Transcription,participant
0,1.0,Quiero cortarme el pelo,NaN,participant1.csv
1,2.0,El libro está en la mesa,NaN,participant1.csv
2,3.0,El carro lo tiene Pedro,NaN,participant1.csv
3,4.0,El se ducha cada mañana,NaN,participant1.csv
4,5.0,¿Qué dice usted que va a hacer hoy?,NaN,participant1.csv

In [42]:
model=whisper.load_model('small')

In [53]:
import os
folder = r'..\data\audio'
transcriptions = []
for file in os.listdir(folder): 
    if file.endswith(".mp3"):    
        audio_path = os.path.join(folder, file)  
        print("processing",file)
        result = model.transcribe(audio_path, language="es")
        full_text = result["text"]
        sentences = re.split(r'[.!?]', full_text)
        sentences = [s.strip() for s in sentences if s.strip()]
        transcriptions.extend(sentences)
len(transcriptions)

processing participant1.mp3
processing participant2.mp3
processing participant3.mp3
processing participant4.mp3

116

In [56]:
data["Transcription"].iloc[:len(transcriptions)] = transcriptions
data.head()

C:\Users\USER\AppData\Local\Temp\ipykernel_6804\1683590571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Transcription"].iloc[:len(transcriptions)] = transcriptions

,Sentence,Stimulus,Transcription,participant
0,1.0,Quiero cortarme el pelo,Quiero cortarme el pelo,participant1.csv
1,2.0,El libro está en la mesa,Quiero cortarme el pelo,participant1.csv
2,3.0,El carro lo tiene Pedro,El libro está en la mesa,participant1.csv
3,4.0,El se ducha cada mañana,El libro está en la mesa,participant1.csv
4,5.0,¿Qué dice usted que va a hacer hoy?,El caro lo tiene el pelo,participant1.csv

In [57]:
data.to_csv("../results/participant_transcription.csv", index=False)